name: Create Pull Request

on:
  push:
    branches:
      - "*"
      - "!main"
      - "!develop"

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          PUSHER_USERNAME: ${{ github.actor }}
        run: |
          TARGET_BRANCH="main"
          SOURCE_BRANCH="${GITHUB_REF#refs/heads/}"

          # Check if PR already exists
          PR_EXISTS=$(gh pr list --base "$TARGET_BRANCH" --head "$SOURCE_BRANCH" --json number --jq 'length')

          if [ "$PR_EXISTS" -eq 0 ]; then
            # Create new PR
            gh pr create \
              --title "AUTO: $SOURCE_BRANCH" \
              --body "Automatically created PR" \
              --base "$TARGET_BRANCH" \
              --head "$SOURCE_BRANCH" \
              --assignee "$REPO_OWNER" \
              --reviewer "$REPO_OWNER"

            echo "Opened a new pull request: AUTO: $SOURCE_BRANCH"
          else
            echo "Pull request already exists for this branch"
          fi
